version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: circleci/python:3.6.8
        steps:
            - checkout
            #- restore_cache:
                #keys:
                    #- v1-dependencies-{{ checksum "setup.py" }}
                    #- v1-dependencies-

            - run:
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    python3 setup.py install
                    pip install tox

            #- save_cache:
                #paths:
                    #- ./venv
                #key: v1-dependencies-{{ checksum "setup.py" }}
            - run:
                name: Apply CodeCov workaround for excluding lines
                command: |
                  # Workaround for https://github.com/codecov/codecov-python/issues/107
                  sed 's/internal_assert(0)/# ignored for CodeCov/' \
                  -i $(find storyscript -type f -name '*.py')
                  #sed 's/from.*internal_assert/# ignored for CodeCov/' \
                  #-i $(find storyscript -type f -name '*.py' \
                  #  -not -name '*__init__.py')

            - run:
                name: run pep8 linter
                command: |
                    . venv/bin/activate
                    tox -e pep8

            - run:
                name: run unit tests
                command: |
                    . venv/bin/activate
                    tox -e unit

            - run:
                name: collect unit coverage
                command: |
                    bash <(curl -s https://codecov.io/bash) -F unittests -f unittest.xml

            - run:
                name: run integration tests
                command: |
                    . venv/bin/activate
                    tox -e integration

            - run:
                name: collect integration coverage
                command: |
                    bash <(curl -s https://codecov.io/bash) -F integration -f integration.xml

            - store_artifacts:
                path: test-reports
                destination: test-reports
    deploy:
        docker:
            - image: circleci/python:3.6.8
        steps:
            - checkout
            - run:
                  name: install dependencies
                  command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    python setup.py install
            - run:
                  name: verify git tag vs. version
                  command: |
                    . venv/bin/activate
                    python setup.py verify
            - run:
                  name: init .pypirc
                  command: |
                    echo -e "[pypi]" >> ~/.pypirc
                    echo -e "username = ${PYPI_USER}" >> ~/.pypirc
                    echo -e "password = ${PYPI_PASSWORD}" >> ~/.pypirc
            - run:
                  name: create packages
                  command: |
                    rm -rf dist
                    rm -rf tests # not needed in the released package
                    . venv/bin/activate
                    python setup.py sdist
                    pip install wheel
                    python setup.py bdist_wheel
            - run:
                  name: upload to pypi
                  command: |
                    . venv/bin/activate
                    pip install twine==1.13.0
                    twine upload dist/*
